Adding Data from last ten years, excluding 2019-2020(COVID), Also adding team ratings data. Then, Merge datasets into master_team_stats

In [5]:
import pandas as pd 
import csv

ratings_data = pd.read_csv('538 Ratings.csv')
team_data_25_26 = pd.read_csv('25-26_data.csv')
team_data_24_25 = pd.read_csv('24-25.csv')
team_data_23_24 = pd.read_csv(' 23-24.csv')
team_data_22_23 = pd.read_csv(' 22-23.csv')
team_data_21_22 = pd.read_csv('21-22.csv')
team_data_20_21 = pd.read_csv(' 20-21.csv')
team_data_18_19 = pd.read_csv(' 18-19.csv')
team_data_17_18 = pd.read_csv('17-18.csv')
team_data_16_17 = pd.read_csv(' 16-17.csv')
team_data_15_16 = pd.read_csv(' 15-16.csv')

team_data_25_26['Season'] = '2025-26'
team_data_24_25['Season'] = '2024-25'
team_data_23_24['Season'] = '2023-24'
team_data_22_23['Season'] = '2022-23'
team_data_21_22['Season'] = '2021-22'
team_data_20_21['Season'] = '2020-21'
team_data_18_19['Season'] = '2018-19'
team_data_17_18['Season'] = '2017-18'
team_data_16_17['Season'] = '2016-17'
team_data_15_16['Season'] = '2015-16'

all_seasons = [
    team_data_15_16, team_data_16_17, team_data_17_18, team_data_18_19,
    team_data_20_21, team_data_21_22, team_data_22_23, team_data_23_24,
    team_data_24_25, team_data_25_26
]

master_team_stats = pd.concat(all_seasons, axis=0, ignore_index=True)

master_team_stats.head(10)

,Unnamed: 0,Unnamed: 1,Overall,Overall.1,Overall.2,Overall.3,Overall.4,Overall.5,Unnamed: 8,Conf.,...,Totals.8,Totals.9,Totals.10,Totals.11,Totals.12,Totals.13,Totals.14,Totals.15,Totals.16,Season
0,Rk,School,G,W,L,W-L%,SRS,SOS,NaN,W,...,FTA,FT%,ORB,TRB,AST,STL,BLK,TOV,PF,2015-16
1,1,Abilene Christian,31,13,18,0.419,-13.93,-7.53,NaN,8,...,653,0.701,269,991,422,233,78,418,681,2015-16
2,2,Air Force,32,14,18,0.438,-5.51,0.66,NaN,5,...,707,0.683,285,1107,420,196,58,423,617,2015-16
3,3,Akron,35,26,9,0.743,5.55,-1.24,NaN,13,...,659,0.684,373,1310,507,190,137,381,618,2015-16
4,4,Alabama,33,18,15,0.545,7.14,8.62,NaN,8,...,712,0.643,327,1141,347,192,175,438,631,2015-16
5,5,Alabama A&M,29,11,18,0.379,-13.47,-10.75,NaN,6,...,642,0.684,330,1000,366,163,61,340,561,2015-16
6,6,Alabama State,31,14,17,0.452,-13.11,-9.35,NaN,9,...,623,0.684,391,1153,372,181,107,371,646,2015-16
7,7,Albany (NY),33,24,9,0.727,0.93,-7.57,NaN,13,...,814,0.751,387,1276,410,216,52,413,581,2015-16
8,8,Alcorn State,30,15,15,0.5,-16.01,-9.94,NaN,13,...,676,0.678,384,1072,272,134,111,429,548,2015-16
9,9,American,31,12,19,0.387,-14.18,-6.08,NaN,9,...,471,0.696,218,874,348,176,69,428,566,2015-16

Clean the data

In [19]:
df = master_team_stats
df = df.rename(columns={'Unnamed: 1': 'School' })
df = df[df["School"].str.contains("NCAA", case=False, na=False)]

df = df.rename(columns={'Overall': 'Games', 'Overall.1': 'Wins', 'Overall.2': 'Losses', 'Overall.3': 'W-L %', 'Overall.3': 'W-L %',
'Overall.4': 'SRS', 'Overall.5': 'Strength of Schedule', 'Conf.': 'Conf. Wins', 'Conf..1': 'Conf. Losses', 'Home': 'Home Wins', 'Home.1':'Home Losses',
'Away': 'Away Wins', 'Away.1': 'Away Losses', 'Points.1': 'Opp. Points', 'Totals': 'Minutes Played', 'Totals.1': 'FG', 'Totals.2': 'FG Att.', 'Totals.3': 'FG %',
 'Totals.4': '3 Pts', 'Totals.5': '3pt att.', 'Totals.6': '3pt %', 'Totals.7': 'FT', 'Totals.8': 'FT att.', 'Totals.9': 'FT %', 'Totals.10': 'Offensive RB', 
 'Totals.11': 'Total RB', 'Totals.12': 'Assists', 'Totals.13': 'Steals', 'Totals.14': 'Blocks', 'Totals.15': 'Turnovers', 'Totals.16': 'PF'})

df = df.drop(columns=[ 'Unnamed: 0', 'Unnamed: 8', 'Unnamed: 11', 'Unnamed: 14', 'Unnamed: 17', 'Unnamed: 20'])


pd.set_option('display.max_columns', None)
df.head(10)

,School,Games,Wins,Losses,W-L %,SRS,Strength of Schedule,Conf. Wins,Conf. Losses,Home Wins,Home Losses,Away Wins,Away Losses,Points,Opp. Points,Minutes Played,FG,FG Att.,FG %,3 Pts,3pt att.,3pt %,FT,FT att.,FT %,Offensive RB,Total RB,Assists,Steals,Blocks,Turnovers,PF,Season
11,Arizona NCAA,34,25,9,0.735,18.79,7.23,12,6,17,1,5,5,2735,2342,1390,946,1970,0.48,221,580,0.381,622,863,0.721,394,1368,485,164,161,442,621,2015-16
18,Austin Peay NCAA,36,18,18,0.5,-6.04,-2.98,7,9,7,7,7,9,2740,2765,1460,945,2049,0.461,223,645,0.346,627,936,0.67,422,1326,479,250,101,502,633,2015-16
20,Baylor NCAA,34,22,12,0.647,16.13,9.76,10,8,15,5,6,5,2621,2366,1375,933,2003,0.466,210,572,0.367,545,752,0.725,467,1267,603,269,135,432,660,2015-16
33,Buffalo NCAA,35,20,15,0.571,1.34,0.9,10,8,10,5,5,9,2709,2634,1410,915,2096,0.437,263,776,0.339,616,867,0.71,425,1363,441,240,124,475,748,2015-16
34,Butler NCAA,33,22,11,0.667,16.46,7.55,10,8,13,3,5,5,2638,2344,1325,918,1969,0.466,236,601,0.393,566,774,0.731,366,1188,468,227,107,335,646,2015-16
36,Cal State Bakersfield NCAA,33,24,9,0.727,2.58,-5.15,11,3,14,1,7,7,2405,2104,1330,875,1939,0.451,179,524,0.342,476,726,0.656,414,1263,516,263,165,405,707,2015-16
39,California NCAA,34,23,11,0.676,15.39,7.87,12,6,18,0,4,7,2545,2289,1375,890,1931,0.461,236,651,0.363,529,806,0.656,386,1349,430,139,159,419,706,2015-16
47,Chattanooga NCAA,35,29,6,0.829,3.24,-3.46,15,3,13,1,10,4,2652,2364,1410,897,1963,0.457,262,729,0.359,596,811,0.735,381,1241,504,272,165,437,596,2015-16
49,Cincinnati NCAA,33,22,11,0.667,15.19,5.25,12,6,14,3,6,6,2418,2090,1355,851,1980,0.43,252,725,0.348,464,658,0.705,441,1291,508,257,192,363,513,2015-16
55,Colorado NCAA,34,22,12,0.647,12.04,7.64,10,8,16,1,4,7,2576,2407,1370,865,2029,0.426,252,647,0.389,594,808,0.735,446,1434,461,177,167,454,638,2015-16